# Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

# Import required packages
import unittest
from add import add_numbers

class AddNumbersTestCase(unittest.TestCase):

    def test_add_numbers_4beee899f4(self):
        # Test case 1: Testing with positive integers
        result = add_numbers(5, 4)
        self.assertEqual(result, 9, msg="Test failed. Expected 9 but got {}".format(result))

        # Test case 2: Testing with negative integers
        result = add_numbers(-5, -3)
        self.assertEqual(result, -8, msg="Test failed. Expected -8 but got {}".format(result))

        # Test case 3: Testing with zero
        result = add_numbers(0, 5)
        self.assertEqual(result, 5, msg="Test failed. Expected 5 but got {}".format(result))

        # Test case 4: Testing with positive and negative integers
        result = add_numbers(-5, 5)
        self.assertEqual(result, 0, msg="Test failed. Expected 0 but got {}".format(result))

        # Test case 5: Testing with floats
        result = add_numbers(3.5, 2.5)
        self.assertEqual(result, 6, msg="Test failed. Expected 6 but got {}".format(result))

if __name__ == '__main__':
    unittest.main()
