# Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

import unittest
from calculate import judge_leap_year

class TestJudgeLeapYear(unittest.TestCase):
    
    def test_judge_leap_year(self):
        # Test leap year
        self.assertEqual(judge_leap_year(2000), True)
        # Test non-leap year
        self.assertEqual(judge_leap_year(2001), False)
        # Test year that is a multiple of 100 but not 400
        self.assertEqual(judge_leap_year(1900), False)
        # Test year that is a multiple of 4 but not 100
        self.assertEqual(judge_leap_year(2020), True)

if __name__ == '__main__':
    unittest.main()
