# Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

# necessary import for testing
import unittest
from add import add_numbers  # assuming the function is in a file named 'add.py'

# define Test class extended from unittest.TestCase
class TestAddNumbers(unittest.TestCase):
    def test_Add_numbers_4beee899f4(self):
        # TODO: place the values for num1 and num2, test with different values

        # test for simple addition
        self.assertEqual(add_numbers(1, 2), 3)

        # test with negative values
        self.assertEqual(add_numbers(-1, 2), 1)

        # test with zero
        self.assertEqual(add_numbers(0, 2), 2)

        # test with two negative values
        self.assertEqual(add_numbers(-1, -2), -3)

        # test with floating point values
        self.assertEqual(add_numbers(1.0, 2.0), 3.0)


# main method to run the tests
if __name__ == "__main__":

    # this module will be responsible to load and run the tests
    unittest.main()

