# Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

import calculate
import unittest

class TestCalculate(unittest.TestCase):

    def test_judge_leap_year(self):
        # Leap years
        self.assertEqual(calculate.judge_leap_year(2000), True)
        self.assertEqual(calculate.judge_leap_year(2004), True)
        
        # Non-leap years
        self.assertEqual(calculate.judge_leap_year(2001), False)
        self.assertEqual(calculate.judge_leap_year(1900), False)

if __name__ == '__main__':
    unittest.main()
