# Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

import time
from calendar import isleap
from calculate import month_days
import unittest

class TestCalculate(unittest.TestCase):

    # Test if month_days function correctly count number of days in February in a leap year
    def test_month_days_5dd3c5e333_a(self):
        result = month_days(2, True)
        self.assertEqual(result, 29, 'Failed to count days in February of a leap year.')

    # Test if month_days function correctly counts number of days of months except February
    def test_month_days_5dd3c5e333_b(self):
        result_31days_months = [month_days(month, False) for month in [1, 3, 5, 7, 8, 10, 12]]
        result_30days_months = [month_days(month, False) for month in [4, 6, 9, 11]]
  
        for days in result_31days_months:
            self.assertEqual(days, 31, 'Failed to count days in 31-day months.')

        for days in result_30days_months:
            self.assertEqual(days, 30, 'Failed to count days in 30-day months.')


# Run all defined unit tests
if __name__ == '__main__':
    unittest.main()
