# Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

import calculate
import unittest
import time
from calendar import isleap

# Mocking the input() function
calculate.input = lambda _: "30"  # for age
calculate.input = lambda _: "John Doe"  # for name

# Mocking the time.localtime() function
class MockTime:
    def __init__(self, year, month, day):
        self.tm_year = year
        self.tm_mon = month
        self.tm_mday = day

calculate.time.localtime = lambda _: MockTime(2022, 1, 1)

class TestCalculate(unittest.TestCase):
    def test_month_days(self):
        self.assertEqual(calculate.month_days(1, True), 31)
        self.assertEqual(calculate.month_days(2, True), 29)
        self.assertEqual(calculate.month_days(2, False), 28)
        self.assertEqual(calculate.month_days(12, True), 31)

    # TODO: Add more test methods here

if __name__ == "__main__":
    unittest.main()
